### PR TITLE
Rework of RTC and regulator module

### PR DESCRIPTION
**Pull request by dr-stefan-krank**
Rework of regulator and RTC.
Open for review.

### CODE REVIEW

**Comment by wassfila** [comment]
looks good to me, but can you maybe specify roughly what the rework was ?

**Comment by dr-stefan-krank** [comment]
Moved the cut-off mosfet to the regulator module and instead just routed the INT from the RTC to it.
Added EN connections for the additional regulators to the MCU board, so they can be switched with GPIOs.
Didn't add the hierarchical labels on the MCU sheet itself, to prevent conflicts with the MCU branch.

**Comment by wassfila** [comment]
Yeah @dr-stefan-krank well done, regarding the MCU sheet maybe you can help in #36 as @2010019970909 is a bit busy with studies these times. I don't think we have to redo anything in there just fixing the DRC and merging at a first step, we can discuss it Today.

**Comment by Vincent-Stragier** [comment]
Yep, any help is welcome.
I've tried to track the changes that have still to be done [here](https://github.com/Informaticore/SuperPower/projects/4).

For the DRC, on the MCU sheet, there is only one relative to the MCU (one pin of the pins header not connected, which is related to the replication of the low cost version which I did not do yet). The rest of the DRC errors is on other sheets. Also there was two remarks on #39 (one about using net label (I suppose for the voltages, etc., but they are global one in KiCad, so we have to be in sync).

**Comment by wassfila** [comment]
> Yep, any help is welcome.
> I've tried to track the changes that have still to be done [here](https://github.com/Informaticore/SuperPower/projects/4).
> 
> For the DRC, on the MCU sheet, there is only one relative to the MCU (one pin of the pins header not connected, which is related to the replication of the low cost version which I did not do yet). The rest of the DRC errors is on other sheets. Also there was two remarks on #39 (one about using net label (I suppose for the voltages, etc., but they are global one in KiCad, so we have to be in sync).

ok, I shifted these comments on #43 and we'll mix them with the TODO from the project

**Comment by wassfila** [comment]
## Team review
- to check the pull up again before merge
- to add pull up on RTC sheet or on the regulators sheet
- cutoff enable in stead of VIN possible

**Review by wassfila — APPROVED** [review]
Looks good now, I checked everything opens without issues, interactions required with the mcu sheet so better go through the master.
If any findings are noticed after this merge they should simply be documented on a ticket.

**Pull request merged**
