### PR TITLE
Complete rework of regulator design

### PR DESCRIPTION
**Pull request by dr-stefan-krank**
Removed the old regulator in favor of the TPS63070 and TPS709.
Rewired the RTC and I2C pullups to the TPS709.
Moved the I2C pullups on the RTC sheet.

### CODE REVIEW

**Comment by wassfila** [comment]
Reference that we're converging to :
image

**Comment by wassfila** [comment]
TPS63070RNMT does not have a datasheet link, no rework needed for it, just a notice.
not sure which pdf link is best, I found this : 
https://www.ti.com/lit/ds/symlink/tps63070.pdf

**Comment by wassfila** [comment]
For the 5V boost reg, I'm not sure about this so just a question, does the enable not require a pull up to vin like the mcu reg ? in this case it is directly driven from the uC without mosfet :
image

**Comment by Tobi3566** [comment]
> 
> 
> For the 5V boost reg, I'm not sure about this so just a question, does the enable not require a pull up to vin like the mcu reg ? in this case it is directly driven from the uC without mosfet :
> 

no. the enable pin compares to a 0.8V so any ttl logic can drive it

**Comment by Tobi3566** [comment]
also i think that the EN pin on the MCU regulator needs a pulldown to disable the when not in use. (would otherwise be floating)

**Comment by wassfila** [comment]
> also i think that the EN pin on the MCU regulator needs a pulldown to disable the when not in use. (would otherwise be floating)

That's an important finding, you're right, I think it's worth a rework.

**Review by wassfila — CHANGES_REQUESTED** [review]
as mentioned @Tobi3566 , floating enable of the 5v boost when uC powered off, should have a pull down

**Comment by wassfila** [comment]
@Tobi3566 the reason I mentioned is that in the datasheet they don't explicitly mention it like that so I'm not sure we can trust the logic inside the chip without it being in the spec : 
image

**Comment by Tobi3566** [comment]
@wassfila they mention it in the pin descriptions a few pages below XD
also why would anyone build a converter chip that doesn't accept logic level inputs for signal pins ¯\_(ツ)_/¯

**Comment by wassfila** [comment]
> @wassfila they mention it in the pin descriptions a few pages below XD
> also why would anyone build a converter chip that doesn't accept logic level inputs for signal pins ¯_(ツ)_/¯

OK, right, thanks @Tobi3566 for the notice, well verification is all about not to trust anyone lol
image

**Comment by Informaticore** [comment]
image
here is a comment with 0603 and 0805 - the values are all the same but why the difference in package?

**Comment by Informaticore** [comment]
> Reference that we're converging to :
> image

Thank you for using that amazing drawing as a reference :D

**Comment by MantaRayDeeJay** [comment]
I'm not sure that 10uF capacitors at the input stage of the TPS63070 can be in 0805/0603 packages.
Input voltage can reach 16V.
I think we should use 25V - 1206 - X7R capacitors.

**Comment by dr-stefan-krank** [comment]
> image
> here is a comment with 0603 and 0805 - the values are all the same but why the difference in package?

I just went with the datasheet:
image

image

**Comment by MantaRayDeeJay** [comment]
> 
> > here is a comment with 0603 and 0805 - the values are all the same but why the difference in package?
> 
> I just went with the datasheet:
> 
> 
> 

So Input capacitor is well 1206 size (3.2x1.6) for Vin>8V !

10µF 0603 25V seems to be only available in X5R.
X5R is enough but in case we want to use X7R, we need to choose a greater case.
https://eu.mouser.com/ProductDetail/Taiyo-Yuden/TMK107BBJ106MA-T?qs=%2Fha2pyFadugnoQLFseJyyLDYjvNgWCM4GFyzGQT9IcWRhsOq4%252BW9Ag%3D%3D

10µF 0805 25V seems to be only available in X7S.
X7S is enough but in case we want to use X7R, we need to choose a greater case.
https://eu.mouser.com/ProductDetail/Murata-Electronics/GRM21BC71E106ME11L?qs=K0Sa7bCb58Jn3x6%2FgoOqlA%3D%3D

**Review by wassfila — APPROVED** [review]

**Comment by wassfila** [comment]
pull down added

**Pull request merged**
