### PR TITLE
Rework pins headers, add improvements and solve DRC on all the sheets

### PR DESCRIPTION
**Pull request by Vincent-Stragier**

### CODE REVIEW

**Comment by Informaticore** [comment]
image
if they are not used we should remove the labels and cross them out directly on the symbol

image
not anymore right? :) 

image
what is this 2 for? And I would leave VBUS from being pinned out - we have 5V and 3v3 which should be fine. On the DevKitBoards they pinout it with VIN. But I think there is no real need for us to make it a pin because we already have 5v and 3v3 as outputs. and for inputs we have the charger I/O which might be only I and no O

- the 3v3 and 5v enable pins need to be connected to the MCU but we can discuss which one to use in our sunday meeting

image
can you remove the track and make the vbus a local label for all pins here? I first thought that the VBUS was not connected to the MCU but then found the label on the left side. I felt a bit hidden.

**Comment by wassfila** [comment]
impressive work I must admit, I had a look that all the mentioned commits are there, lots of DRC errors removed. Not sure why "Work in Progress" is there, the whole project is generally a work in progress until it is released.

**Review by wassfila — APPROVED** [review]
approved but I won't merge as @2010019970909 wanted maybe more people to review here on this PR.
So you can decide when you want to merge it before conflicts are created with the master.

**Review by wassfila — CHANGES_REQUESTED** [review]
just to wait and check conflicts with the charger branch

**Review by wassfila — DISMISSED** [review]

**Comment by Vincent-Stragier** [comment]
- For the not connected nets with labels, it's not important to remove them (might be used later).
- I did remove the 'WORK IN PROGRESS' text, even if there is still some work to do (like adding the configuration headers on the MCU sheet).
- For the 2, it refers to the Note 2 (in order to "avoid" confusion between the VBUS on the board and the VBUS which serves to sense the board VBUS on the USB-UART bridge).
- Also it might be interesting to keep VBUS there, since you can remove the USB-C VBUS 0 Ohm resistor to disconnect the voltage bus (and thus having VBUS on the headers allows you to power the chip, because the 5 V regulator is not always on, etc.).
- I will change charger IO to charger inputs (done, it's renamed 'Charger inputs and USB IO').
- I did move the power oring (the MOSFET whom I added on the charger IC sheet).
- I did remove the solar input but I did reuse the connector for the previously name VOUT net on the charger IO sheet (VOUT is now V_CHARGE).
- I did change the wiring between the modules.
image

**Comment by Vincent-Stragier** [comment]
I've renamed and removed all the labels used to enable the regulators (either by connecting them to VIN or to driving them with a GPIO). I suggest to put them in front of specific GPIO and between those GPIO and headers, which will allow to use real jumper and not wires.
image

**Review by wassfila — DISMISSED** [review]
looks good for now.
This branch is increasing in size, so should not get very big before syncing with main so that other branches do not deviate much.

**Review by MantaRayDeeJay — APPROVED** [review]
Let's go ahead

**Pull request merged**
