### PR TITLE
Enable SVG generation for GitHub Action

### PR DESCRIPTION
**Pull request by Informaticore**

### CODE REVIEW

**Review by Vincent-Stragier — DISMISSED** [review]

**Comment by wassfila** [comment]
I assume WIP means not to be reviewed yet

**Comment by wassfila** [comment]
related relevant issues than might be solved here :
#25
#26
#27

**Comment by Vincent-Stragier** [comment]
> I assume WIP means not to be reviewed yet

Did not catch it xD (Work In Progress)

Edit: Maybe it should be a draft PR.

**Comment by Informaticore** [comment]
It is common (at least in GitLab) that you add "WIP:" infront of the PR to make it work in progress. Somehow GitHub does not have this feature

**Comment by Vincent-Stragier** [comment]
> It is common (at least in GitLab) that you add "WIP:" infront of the PR to make it work in progress. Somehow GitHub does not have this feature

Apparently the [draft mode](https://github.com/isaacs/github/issues/416#issuecomment-464753399) is here for that reason (but it does not totally solve the problem). And it's possible to [convert a PR to draft](https://github.blog/changelog/2020-04-08-convert-pull-request-to-draft/).

**Review by wassfila — APPROVED** [review]
generated doc tested with pan zoom

**Pull request merged**
