### PR TITLE
Lowcost/feature/multiple

### PR DESCRIPTION
**Pull request by Tobi3566**
toplevel components and lowcost with rtc, charger, protection, io expander and some auxillary stuff

### CODE REVIEW

**Comment by wassfila** [comment]
got an error when opening
image

image

**Comment by wassfila** [comment]
not very clear if the sub schematics are to review or I assume they're a work in progress.

**Review by wassfila — DISMISSED** [review]
looks fine now from files and integration point of view, schematics do not seem to be finalized so won't make a deep review of them, I still recommend to give the chance for more reviews before merge.

**Review by Vincent-Stragier — COMMENTED** [review]
Seems good to me too. To summarize, you did mostly add .lib and edit the schematics. And I do not approve for the reason mentioned above.

**Comment by wassfila** [comment]
> Seems good to me too. To summarize, you did mostly add .lib and edit the schematics. And I do not approve for the reason mentioned above.
@2010019970909 
Maybe we should let it go and merge it, it's been pending more than 24h so everyone had a chance to look.
Also it would be good that we use same components in the next branch feature/mcu that we can create after this pr is merged.

**Comment by Tobi3566** [comment]
pushed 4 more commits that conclude the first schematic layout that is to be discussed about now

**Comment by wassfila** [comment]
@Tobi3566 
if possible to document the Kicad version in the readme as you're the first to face this issue, I also have the warning about the version
https://github.com/Informaticore/SuperPower/blob/master/SuperPower-uC/README.md
@Informaticore says the version does not matter as long as it is 5.x.x but such warnings are quite annoying and I'm not sure it works afterward.
I'll update to v5.1.7, documenting this on the read me can come in this PR or next one, that's ok

**Comment by Informaticore** [comment]
It matters when it comes to libraries. There is an old format and a new one

**Comment by Informaticore** [comment]
You maybe also rename the main .sch file to something like SuperPower-uC-lowcost.sch or something - if I open them back and forth it is hard to determine the two versions

**Comment by Informaticore** [comment]
image

still broken but now with new components, are those KiCad default symbols?

**Comment by wassfila** [comment]
@Informaticore for me, both variants open smoothly without complaints, are you sure you don't have many Kicad versions installed ? Or if your repo is clean ?

**Comment by wassfila** [comment]
> You maybe also rename the main .sch file to something like SuperPower-uC-lowcost.sch or something - if I open them back and forth it is hard to determine the two versions

I would not recommend that, both project should be as similar as possible and for Kicad they're completely independent, renaming would make their comparison more complex.

**Comment by Tobi3566** [comment]
i updated to 5.1.7 and replaced the usb-c part cause that gave me an error after that.
maybe @Informaticore your kicad librarys are out of date?

**Comment by Informaticore** [comment]
image

1. the input cap shouls be 1uF not 0.1uF
2. the setup for the LC709203F is the one including the Thermistor on the battery side with 10k - if there is no thermistor you might need to add a "fake" value to fake 25°? no?

**Comment by Tobi3566** [comment]
the 0.1u is not critical and should be sufficient. for not having a thermistor you'd not populate the other 2 resistors for the chip to know.
*i'll change the .1 to a 1u later tho

**Comment by Informaticore** [comment]
You should try to avoid crossings of tracks which are not connected. sometimes it is harder to read.
image

My suggestion also is to translate the hirachical-labels into local NETs just to not miss them out or oversee them in the schematic. I hope it is okay, I did not push it like this but I tried to rearrange the schematic like this:
image

I think it is much more readable :) please don't be angry with me and my nitpicking.

**Comment by Vincent-Stragier** [comment]
> You should try to avoid crossings of tracks which are not connected. sometimes it is harder to read.
> image
> 
> My suggestion also is to translate the hirachical-labels into local NETs just to not miss them out or oversee them in the schematic. I hope it is okay, I did not push it like this but I tried to rearrange the schematic like this:
> image
> 
> I think it is much more readable :) please don't be angry with me and my nitpicking.

I'd add that the ground always comes from the bottom and power supply from the top (so I'd change the direction of the GND labels and other powers supply related labels).

**Comment by Tobi3566** [comment]
the crossing of tracks is mostly personal preferrence tho (i don't like splitting everything for two tracks that cross each other) ¯\_(ツ)_/¯

**Comment by wassfila** [comment]
@Informaticore this is not really being picky they're all fair statements. But maybe what makes them a bit difficult to apply is when you keep discovering the rules all along a review. You provided some useful documentation about schematics good practices, but you did not set any rules of what should acceptable and what not, therefore, I think we should be a bit open here otherwise the boards might not see the light lol
Or at least, after this PR is through, you can list a set of rules that we start applying even in existing schematics.

**Review by wassfila — APPROVED** [review]
All findings are related to style which does not have any clear rule, the schematics look clean enough for a start, I agree with the GND pointing down, I got confused by that, but totally for a next time that's the sort of refactoring that can be done at the end, or afterwards.

**Review by Vincent-Stragier — APPROVED** [review]

**Pull request merged**
