### PR TITLE
Add S2B-PH-SM4-TB(LF)(SN) component name

### PR DESCRIPTION
**Pull request by Informaticore**

### CODE REVIEW

**Comment by wassfila** [comment]
Haha, now this PR throws complaints with 5.1.7 getting funny :)
image

**Comment by wassfila** [comment]
paths
image

**Comment by wassfila** [comment]
now opening without complaints

**Review by wassfila — APPROVED** [review]
now opening without complaints

**Review by Tobi3566 — APPROVED** [review]

**Pull request merged**
