### PR TITLE
Regulator Module schematics

### PR DESCRIPTION
**Pull request by dr-stefan-krank**

### CODE REVIEW

**Comment by Tobi3566** [comment]
grafik
1. components don't show. might need to be set as local (for the new one) and included in the sym-lib-table.
2. don't know if we and to use bypass jumpers or solder bridges
3. mcu regulator should be connectod to INT line which is still missing on the original variant

**Comment by dr-stefan-krank** [comment]
>     1. components don't show. might need to be set as local (for the new one) and included in the sym-lib-table.
Yes, they have to be included. All extra components should be linked in the sym-lib-table. One should create one and merge it into master.
> 
>     2. don't know if we and to use bypass jumpers or solder bridges
Me neither, but I had solder pads in my other draft and was told to replace them for pin headers. Pin headers are easier to set and unset. One can place a wire bridge instead of a through hole header for a permanent solution.

We need a design rule for that.
> 
>     3. mcu regulator should be connectod to INT line which is still missing on the original variant
INT Line and corresponding P-MOSFET is on the RTC sheet. MCU regulator is switched via VIN, not EN pin.

**Review by wassfila — CHANGES_REQUESTED** [review]
As discussed between @Tobi3566  and @dr-stefan-krank this Branch still have TODOs, I think the minimal requirement for a PR is that the components are viewable and not show question marks, I suggest that it should be something that does not go to the master.

**Comment by wassfila** [comment]
regulators are now viewable so I check my change request

**Review by wassfila — DISMISSED** [review]

**Comment by wassfila** [comment]
DRC Errors stills
image

**Review by wassfila — APPROVED** [review]
fixed DRC error with passive

**Comment by wassfila** [comment]
not important for now, so change is not mandatory, but for info we might have some pin overlaps 
image

And that for three pins 
- SW
- VOUT
- PGND

**Review by MantaRayDeeJay — APPROVED** [review]

**Pull request merged**
