### PR TITLE
Feature/battery module

### PR DESCRIPTION
**Pull request by MantaRayDeeJay**

### CODE REVIEW

**Comment by wassfila** [comment]
I have a not found component, maybe you should rather add it to the repo local components directory and use it from there ?
image

**Comment by wassfila** [comment]
I don't know what the others opinion is, but the components prices do not seem to me like something to be documented in the schematics
image

**Comment by Tobi3566** [comment]
i'd personally swap the 0ohm with a open solder bridge and also starting to add packages and part numbers (lcsc, mouser...) might also be useful (easier to search for prices). also don't know why it doesn't load the chip in the schematic

**Review by Tobi3566 — DISMISSED** [review]

**Comment by MantaRayDeeJay** [comment]
> I have a not found component, maybe you should rather add it to the repo local components directory and use it from there ?
> image

It should be done now !!!
PS : Symbol reference was global. I have updated to local.

**Review by Tobi3566 — DISMISSED** [review]

**Review by Tobi3566 — APPROVED** [review]

**Review by wassfila — APPROVED** [review]
fixed requested changes about component local lib

**Comment by wassfila** [comment]
> 
> 
> i'd personally swap the 0ohm with a open solder bridge and also starting to add packages and part numbers (lcsc, mouser...) might also be useful (easier to search for prices). also don't know why it doesn't load the chip in the schematic

@Tobi3566 I assume that this comment was a non blocking comment for the PR. Otherwise it is important that you "request a change" from your review which shows to others that the PR should not yet be merged until you agree your requested change is in.
If this is a note for an improvement in another PR, then it's a good idea to add it in an issue ticket so that it does not get forgotten.
Once we have spare time, we go through the tickets to find TODOs but it's not convenient to be looking PR comments again.

**Pull request merged**
