### PR TITLE
Lowcost/no mcu

### PR DESCRIPTION
**Pull request by Tobi3566**
added a lowcost version intended for use with other dev boards

### CODE REVIEW

**Comment by wassfila** [comment]
I still can see the mcu in the no mcu branch, or did I miss the concept ?
Also, do you intend to keep this as a release branch ? or merge it in the master on its own variant ?
image

**Comment by Tobi3566** [comment]
you are looking in the wrong folder

**Comment by wassfila** [comment]
ah, now I got it, but what is really the benefit ? Is it that hard to simply delete the mcu ? Cannot anyone just do it by himself for any variant ? Because otherwise just removing the mcu would require the double number of all variants we end up with. And then if you do a change on one folder, you need to maintain it on the other "no-mcu" folder.
Maybe adding a ready to produce artefact with a release pack could be of interest but not the full variant, I don't know.
image

**Comment by Tobi3566** [comment]
was more meant as a pure project battery pack kinda board like andreas mentioned in his video. and i agree it doesn't really fit in the folder structure there. could just leave it as a seperate brans as it is not needed atm

**Comment by wassfila** [comment]
yeah probably, I like the idea but it is more an integration issue.
My perfect solution would be, if we could with a command line or some python, delete a component and launch a reroute, so that when you push changes you get two versions generated one with mcu and one without :)
I think keeping it in a "release/lowcost_nomcu_v1" branch is absolutely ok, as this is anyway a step that would have to be reapplied in case of major changes and new release.
you should also think of either branching or at least tagging the lowcost version, for example tag the versions you order, and the "release/lowcost_v1" for example could require a branch in case you'd like to mark the version on the pcb itself and push it on a branch then tag it.

**Pull request closed without merging**
