### PR TITLE
Add MCU and USB-UART bridge and related components

### PR DESCRIPTION
**Pull request by Vincent-Stragier**
Adds the MCU, USB-UART chip (+ RXT and TXT LEDs), I²C pull-up resistors, autoflash/reset, soft start circuit and main MCU headers.

This is a draft because the MCU and main headers are not wired yet and no DRC have been executed yet.

### CODE REVIEW

**Comment by MantaRayDeeJay** [comment]
I think that you should replace the "sym-lib-table" file by the file in the Master branch to hope solving the conflict.
Capture d’écran (389)

**Comment by MantaRayDeeJay** [comment]
What is "GitHub\SuperPower\SuperPower-uC\original\tmp_library.dcm" file ?

**Comment by wassfila** [comment]
@2010019970909 I'm going to give it a shot on trying to solve the conflicts
image

**Comment by wassfila** [comment]
I performed a local merge and looks good so far
image

**Comment by wassfila** [comment]
TODO annotation
image

**Comment by wassfila** [comment]
Checks are failing because annotation is not done, but that is normal as the branch is not ready for reviews yet

**Review by wassfila — APPROVED** [review]
some ERC remaining for missing connections but important to bring the mcu to master so that from now on fixed can start overall from the master

**Pull request merged**
