### PR TITLE
Lowcost/fixes

### PR DESCRIPTION
**Pull request by Tobi3566**
moved the pin headers inward and did some more routing optimisation

### CODE REVIEW

**Comment by Vincent-Stragier** [comment]
Hello,

Here is what I've seen:

Those pads are not perfectly aligned (you can use the properties to align them exactly):
image

Reduce the use of angles (angles act as antenna on the board):
image

Prefer (it's even better if you manage to round the joints):
image

The shield should be floating on the device side (grounded on the host side), so 6 (GND) should be not connected:
image

The UART lines are quite long (might leds to instability at high speed). Also, RX and TX are both named RX (that's not ideal).
image
RX and TX don't have the same lenght (it can introduce an uneven delay in the signal, though it's probably not important for the UART)
image

However D+ and D- are a diffential pair, so the attention to the tracks' lenghts shoud'nt be neglected.
image
You can use the differential routing/tuning tool for that:
image

Here, I'd add a ground area. Even if we are designing a low power board, thermal dissipation is still important. And also a lot a via to avoid creating an antenna:
image

I'll go for that 'overkill' ground plane:
image

If you want I can commit these changes here (differential pair, ground plane and two angles removed).

**Comment by Vincent-Stragier** [comment]
I've also seen this via, which is alone 😢 (it can be removed if it serve no pupose).
image

**Comment by Vincent-Stragier** [comment]
I've spotted some overlaping values:
image

**Review by Vincent-Stragier — APPROVED** [review]
The board is close of being the first prototype.

**Comment by Tobi3566** [comment]
i'll leave this branch open for more fixes

**Pull request merged**
