### PR TITLE
added requirements copied from the spreadsheet

### PR DESCRIPTION
**Pull request by wassfila**
I only added the filtered requirements, I guess more of interest for traceability, I also did not want to put them on the main readme otherwise it might make it boring.
requirements spreadsheet link :
https://docs.google.com/spreadsheets/d/1Awvs3CumJ9qQSrG_uEvt4s6nZwliIjnMdfPibDWA3kU/edit#gid=1880015614&fvid=1986096210

### CODE REVIEW

**Review by Vincent-Stragier — DISMISSED** [review]
All seems good to me.

**Review by Informaticore — COMMENTED** [review]
nice

**Comment by dr-stefan-krank** [comment]
fancy

**Comment by Informaticore** [comment]
Reopened because closing was by accident

**Comment by Informaticore** [comment]
@wassfila you can remove the requirements pdf then so we get rid of binary files. My other PR contains a README where we can merge this list then into later

**Comment by Vincent-Stragier** [comment]
> @wassfila you can remove the requirements pdf then so we get rid of binary files. My other PR contains a README where we can merge this list then into later

Maybe we could add that kind of rules (*.pdf) in the .gitignore?

**Comment by wassfila** [comment]
> 
> Maybe we could add that kind of rules (*.pdf) in the .gitignore?

Well, even Andreas himself has some pdf on his top repo, so it's too hard to restrict this in general. What I highly recommend to avoid is to repetitively keep updating any binary file in each commit, but that is a case that we cannot exclude by rule only by human reviews :)

**Review by Informaticore — APPROVED** [review]

**Review by dr-stefan-krank — APPROVED** [review]
this time for real.

**Pull request merged**
