### PR TITLE
design rule optimisation

### PR DESCRIPTION
**Pull request by Tobi3566**
desing rule fixes

### CODE REVIEW

**Comment by wassfila** [comment]
the branch name is somehow confusing, it's understandable that in the first run you preferred to have one PR as you introduced the whole lot at once, but it is less readable if you keep always using the same branch that has a generic name "multiple". Not a blocker for approval, but I hope you won't keep using the same name branch through the whole project

**Comment by Tobi3566** [comment]
yeah didn't know what else to name it

**Review by wassfila — DISMISSED** [review]
looks much nicer admittedly, multiple rules taken µF naming, centering, top left of interface signals,...

**Comment by Vincent-Stragier** [comment]
I'd change in favor of making the power lines more visible. Also the name of the header is not clear (is it on the right, left, top, bottom of the board). You can also use East, West, North, South. Plus the arrow for the direction of the `TX`/`RX` lines.
image

Here, I'd add a little sentence, since its not clear (what does it override?).
image

For the naming, I think when it starts with a voltage it is a power line... So I'd rather go for `EN_<voltage/regulator>` or `EN_REG_3.3V` instead (since it could be `EN_MCU`).
image

Maybe 10kOhm is too weak to pull-up the line fast enough... (also add a note about why there is a regulator there)
image

Same here, I'd move slightly the GND label from the line and add a note about the `PWR_FLAG`. I'd move the `R1 `too and the add the 100 ohms resistor (as in the datasheet).
image

You have some space, take it ;-)
image

I'd make it like that (we should never connect directly a connecter to another and we should make the connection visible (like avoiding the `R6` case).
image

Same here, take the available space, and make the connection visibles:
image

That's mostly what I had to say. Also for the regulators, the naming is not always the same. I'd go for `Regulator <voltage> (<usage>)`, i.e.,` Regulator 5V (Sensor)`

**Review by wassfila — APPROVED** [review]
already multi stage improvements, should go to the master for next stage of reviews

**Review by Vincent-Stragier — APPROVED** [review]
Some minor changes will have to be applied but we can keep them for later.

**Pull request merged**
