### PR TITLE
Lowcost/feature/battery module

### PR DESCRIPTION
**Pull request by Tobi3566**
fixed the problems, changed to usb-c and added the missing solder jumper
ch340g was chosen because of being a basic part and cheap

### CODE REVIEW

**Comment by wassfila** [comment]
@Tobi3566 would it be possible to keep identical top schematics between low cost and original ? So is the deviation because you're more advanced with changes that would go to the original as well ?

**Comment by wassfila** [comment]
should the USB get annotated ?
image

Also not sure if the schematics are not complete yet, so shifted to the top left not in the center or was that intended ? Not really important, just wondering.

**Review by wassfila — DISMISSED** [review]
fixed requested changes

**Comment by Tobi3566** [comment]
did another request with some more stuff included

**Pull request closed without merging**
