### PR TITLE
Add initial cutoff draft with RTC

### PR DESCRIPTION
**Pull request by dr-stefan-krank**

### CODE REVIEW

**Review by wassfila — DISMISSED** [review]
I approve this PR as I understand is more like learn to practice the PR process.
In general, you only need to PR if you want to share something with another user that'd like to take it from master.
Also the PR blocks your progress, in case you'd like to push you'll stale the previous reviews, but that is ok. You can keep pushing on the same branch.

**Comment by Informaticore** [comment]
TSM2301ACX is still missing

**Comment by wassfila** [comment]
@dr-stefan-krank do you intend to suggest this pull request ? Or do you have still planned changes before ? If so we can close it so that we know when you open it next time that it is time fore review.

**Comment by dr-stefan-krank** [comment]
@wassfila, it's complete now.

**Comment by wassfila** [comment]
1. why does it show now a new file on kicad "rtc_cut_off.sch", also when I open it another file is created in my disk "rtc_cut_off.pro" Is that expected ?
2. Did we decide for a permanent 3.3 LDO ? in stead of powering the rtc from the battery ?
3. Just asking I'm not sure, does it mind if "Conn_01x02_Male" is shorted then INT activated at the same time ?

Other than that looks very clean.

image

**Comment by Informaticore** [comment]
> 1. why does it show now a new file on kicad "rtc_cut_off.sch", also when I open it another file is created in my disk "rtc_cut_off.pro" Is that expected ?
> 2. Did we decide for a permanent 3.3 LDO ? in stead of powering the rtc from the battery ?
> 3. Just asking I'm not sure, does it mind if "Conn_01x02_Male" is shorted then INT activated at the same time ?
> 
> Other than that looks very clean.
> 
> image

1. not sure - happened to me too. but if you use it from the main sheet it works as expected.
2. Yea we didi - we can change it still if we have the LDO

**Comment by wassfila** [comment]
It does not look consistent to me, but at this stage it does not really matter, once we progress with other sections, we can clean that up, but the least would be to commit that "rtc_cut_off.pro" or ".gitignore" it, as it is inconvenient that files pollute the next commit using it.

**Review by wassfila — DISMISSED** [review]
- make sure new files are not generated by simply opening the project "rtc_cut_off.pro" otherwise add it to ".gitignore" file local to that directory.

**Comment by Informaticore** [comment]
> * make sure new files are not generated by simply opening the project "rtc_cut_off.pro" otherwise add it to ".gitignore" file local to that directory.

we should not add this pro file - not sure why it gets created - even the .sch file. It actually should be there since the beginning

**Comment by wassfila** [comment]
OK, you can decide which solution is best, all I suggest is that opening and closing the project should keep the repo clean. many possible solutions :

1. figure out why the file is created and prevent that
2. commit the file : you do not want that
3. ignore the file with .gitignore : 

otherwise it might be committed by mistake next time, or keep following us in all reviews

**Review by wassfila — DISMISSED** [review]
extra schematics fixed, components added

**Review by Informaticore — DISMISSED** [review]

**Comment by Informaticore** [comment]
I figured out an issue wit hthe Vbackup. From the datasheet: Backup Supply Voltage. When the backup switchover function is not needed, VBACKUP must be tied
to VSS with a 10 kΩ resistor. AFAIK Vss is GND and not the supply voltage so it should be tied to Ground, not to VCC via the 10k resistor, right?

**Review by Informaticore — APPROVED** [review]

**Review by wassfila — APPROVED** [review]
checked again, ok

**Pull request merged**
