### PR TITLE
Add Charger Inputs

### PR DESCRIPTION
**Pull request by Informaticore**

### CODE REVIEW

**Review by wassfila — DISMISSED** [review]
Receptacle with data, Solder pads, Screw Terminal and Barrel jack for Solar, looks good

**Review by wassfila — DISMISSED** [review]
Annotations added J1, D1, J3, J4,...

**Review by fabrifer020 — DISMISSED** [review]

**Review by wassfila — APPROVED** [review]
delta review, cachelib added.

**Comment by MantaRayDeeJay** [comment]
Looks good !
Adding the datasheet link about ESD protection IC should be nice.
https://assets.nexperia.com/documents/data-sheet/IP4220CZ6.pdf

**Review by MantaRayDeeJay — APPROVED** [review]

**Pull request merged**
