### PR TITLE
Feature/battery mgm

### PR DESCRIPTION
**Pull request by MantaRayDeeJay**
Added charging module schematic sheet.

### CODE REVIEW

**Comment by wassfila** [comment]
As discussed with @MantaRayDeeJay he will fix the ERC errors

**Comment by wassfila** [comment]
@MantaRayDeeJay You might want to announce when this PR is again ready for reviews. As we see you've been adding commits, it's hard to guess if you're done with changes or if you still have more commits coming ?

**Comment by MantaRayDeeJay** [comment]
> @MantaRayDeeJay You might want to announce when this PR is again ready for reviews. As we see you've been adding commits, it's hard to guess if you're done with changes or if you still have more commits coming ?

It would be OK now !!!

**Comment by MantaRayDeeJay** [comment]
This time, that's OK.
It was my last commit !!!

**Comment by wassfila** [comment]
But Unfortunately I have issues when opening it now
image

What I suggest to solve this is to delete the following files from your directory and make a new commit
image

**Comment by wassfila** [comment]
Also ideally to remove all warning, not only errors, and if a warning has to be left, then a small comment to justify why the warning can be safely ignored :
image

**Comment by MantaRayDeeJay** [comment]
That's very strange...

**Comment by wassfila** [comment]
Yes, the lib compatibility issue is now solved

**Comment by wassfila** [comment]
Most of the warning are due to the work in progress nature of the project, I did not find any alarming one, I think warnings will be worked out collectively on the project step by step.

**Comment by wassfila** [comment]
My suggestion, but not for this PR, rather for the future PR once we discuss this in the team meeting 

- the pcb should be operational for 1 cell out of the box
- undersoldering an soldering 0 ohm and bridges should only be required if a different config 2 or more cells are required

**Comment by MantaRayDeeJay** [comment]
> Most of the warning are due to the work in progress nature of the project, I did not find any alarming one, I think warnings will be worked out collectively on the project step by step.

Yes, I need mainly add some extra hierarchical labels.

**Comment by wassfila** [comment]
Good, this was not clear to me, but as discussed #24 was already fixed by f8f52985ad4d266c95d80645a2a86bfdd51091e9

**Review by wassfila — APPROVED** [review]
all requested changes fulfilled, it's beyond the scope of this PR to be able to have a strong review of the charger IC schematics so that should be ongoing all along the project.

**Review by Tobi3566 — APPROVED** [review]
sym_lib_table should not rely upon rescue lib. (to be done later)

**Pull request merged**
